name: Minecraft Assets Cache

on:
  schedule:
    - cron: "34 3 * * *"
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest
    name: Update Assets Cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: neoforged/actions-modding/minecraft-assets-cache/create@v1
        with:
          minecraft-versions: |
            1.21.1
          minecraft-version-file: gradle.properties
          minecraft-version-regexp: /^\s*minecraft_version\s*=\s*(.+)\s*$/m
